### ISSUE TITLE
review

### ISSUE THREAD

**Issue by ale-strada** [carlosgovi/dwf-m5-desafio#1]
Hola @carlosgovi. Probe el juego y todo funciona bien. Felicitaciones!!. Te dejo como sugerencia revisar el momento donde se muetra la jugada de la Pc estaria bueno hacer otro tipo de animacion, o darle un poco mas de tiempo xq esta un poco confuso.

**Comment by carlosgovi** [comment]
ale como estas e corregido la lógica del mismo mas agregue estilos al seleccionar movimiento de las dos partes tanto player como pc.
