### ISSUE TITLE
review

### ISSUE THREAD

**Issue by FerDR89** [carlosgovi/dwf-m5-desafio#2]
Buenas Carlos, ¿Cómo estas?
Te paso algunos bugs que encontre al momento de jugar

Cuando no elijo ninguna jugada me hace de todos modos la animación como si hubiese seleccionada una:

![image](https://user-images.githubusercontent.com/74626765/199240852-3c464d4a-67ef-4a59-87bb-6db122c1caa3.png)

Al seleccionar una jugada y al momento de llegar a cero me hace una segunda animación sobre una opción que no elegí

![image](https://user-images.githubusercontent.com/74626765/199241008-a93ce911-ec6a-4db8-8e3c-f185feff501e.png)

Y otra cosa más que note es que la animación correspondiente a la jugada de la maquina no se visualiza correctamente.
Para mi esa segunda jugada que se visualiza cuando elijo mi jugada es la jugada de la maquina renderizandose al lado de mi jugada. Recién elegí piedra, hizo la animación correspondiente y a su vez hizo la animación del papel dando el score un "perdiste". Creo que por acá puede estar el problema.

**Comment by carlosgovi** [comment]
los problemas de lógica están resueltos y se agrego estilos para diferenciar el player del pc.
