### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by leandromartin114** [carlosgovi/dwf-m5-desafio#3]
Hola Carlos, Felicitaciones por la web! Te comento algunas cosas que vi al probarla.
1-Cuando no hay puntos te muestra "undefined".
![image](https://user-images.githubusercontent.com/84253648/199815618-ab6db001-596e-483c-a033-83dfe66536cd.png)
2-Ojo con los tamaños de algunas imágenes van con lo justo en versión móvil
![image](https://user-images.githubusercontent.com/84253648/199816521-897386af-37cf-44af-aa09-b84d5183f0c0.png)
Lo demás lo vi bien, éxito en lo que viene!
Saludos.

**Comment by RamiroRiggeri** [comment]
Hola! A lo que comentó Leandro le sumo que se puede elegir más de una opción, deberías buscar un método para que se bloquee una vez que el usuario eligió.

![image](https://user-images.githubusercontent.com/90658617/199831400-3a6aa63e-588a-4c85-b17a-a0080978683a.png)

El resto corrigiendo lo anterior me parece que está bien! Suerte en el próximo módulo

**Comment by carlosgovi** [comment]
hola chicos ya realice los cambios en la lógica de selección y resolví el problema del guardado de los datos en el state
